dist: xenial
language: python
python:
    - '3.8.1'
before_script:
    - pip install pipenv
    - pipenv install
branches:
    only:
        - staging
env:
    - DJANGO_SETTINGS_MODULE=config.settings.travis
script:
    - python manage.py makemigrations
    - python manage.py migrate
    - pipenv run pytest -vv