# Generated by Django 3.1.7 on 2021-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='trial_courses',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name="Nombre de cours d'essai"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('TRIAL', 'Trial')], default='TRIAL', max_length=30, verbose_name="Type d'abonnement"),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Prix de l'abonnement"),
        ),
    ]
