# Generated by Django 3.1.7 on 2021-04-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20210419_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='subscribtion_date',
            field=models.DateTimeField(null=True, verbose_name="Date d'abonnement"),
        ),
    ]
