# Generated by Django 3.2 on 2021-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20210424_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='remaining_trial_courses',
            field=models.IntegerField(blank=True, null=True, verbose_name="Nombre de cours d'essai restants"),
        ),
    ]
