# Generated by Django 3.2 on 2021-05-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20210424_1443'),
        ('membership', '0006_auto_20210424_1446'),
    ]

    operations = [
    ]
