# Generated by Django 3.2 on 2021-05-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_merge_0006_auto_20210424_1443_0006_auto_20210424_1446'),
        ('membership', '0007_usermembership_remaining_trial_courses'),
    ]

    operations = [
    ]
