# Generated by Django 3.1.7 on 2021-03-06 19:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210213_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Contenu'),
        ),
    ]
