# Generated by Django 3.1.6 on 2021-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210220_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reserved_slot',
            field=models.IntegerField(default=0, verbose_name='Places réservées'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slot',
            field=models.IntegerField(default=10, verbose_name='Places disponibles'),
        ),
    ]
