# Generated by Django 3.1.7 on 2021-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Mail')),
                ('subject', models.CharField(max_length=50, verbose_name='Sujet')),
                ('message', models.CharField(max_length=50, verbose_name='Message')),
            ],
        ),
    ]
