# Generated by Django 3.1.7 on 2021-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20210420_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='answer_date',
            field=models.DateTimeField(null=True, verbose_name='Date de réponse'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date du message'),
        ),
    ]
