# Generated by Django 3.2 on 2021-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_auto_20210420_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='answer',
            field=models.CharField(max_length=500, null=True, verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(max_length=500, verbose_name='Message'),
        ),
    ]
