# Generated by Django 3.1.6 on 2021-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210213_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_additional_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informations additionnelles adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code Postal'),
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
