# Generated by Django 3.1.7 on 2021-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210307_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MEMBER', 'Member'), ('VISITOR', 'Visitor')], default='MEMBER', max_length=50),
        ),
    ]
