# Generated by Django 3.2 on 2021-04-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
